//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeWebServiceCSharpSample.BridgeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.bridgemanagement.kurata.jp.net/", ConfigurationName="BridgeServiceReference.BridgeWebService")]
    public interface BridgeWebService {
        
        // CODEGEN: パラメーター 'return' には、パラメーター モードを使用して取得できない追加のスキーマ情報が必要です。具体的な属性は 'System.Xml.Serialization.XmlElementAttribute' です。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bridgemanagement.kurata.jp.net/BridgeWebService/helloRequest", ReplyAction="http://service.bridgemanagement.kurata.jp.net/BridgeWebService/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BridgeWebServiceCSharpSample.BridgeServiceReference.helloResponse hello(BridgeWebServiceCSharpSample.BridgeServiceReference.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bridgemanagement.kurata.jp.net/BridgeWebService/helloRequest", ReplyAction="http://service.bridgemanagement.kurata.jp.net/BridgeWebService/helloResponse")]
        System.Threading.Tasks.Task<BridgeWebServiceCSharpSample.BridgeServiceReference.helloResponse> helloAsync(BridgeWebServiceCSharpSample.BridgeServiceReference.helloRequest request);
        
        // CODEGEN: パラメーター 'return' には、パラメーター モードを使用して取得できない追加のスキーマ情報が必要です。具体的な属性は 'System.Xml.Serialization.XmlArrayAttribute' です。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bridgemanagement.kurata.jp.net/BridgeWebService/getBridgeListReque" +
            "st", ReplyAction="http://service.bridgemanagement.kurata.jp.net/BridgeWebService/getBridgeListRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListResponse getBridgeList(BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bridgemanagement.kurata.jp.net/BridgeWebService/getBridgeListReque" +
            "st", ReplyAction="http://service.bridgemanagement.kurata.jp.net/BridgeWebService/getBridgeListRespo" +
            "nse")]
        System.Threading.Tasks.Task<BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListResponse> getBridgeListAsync(BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://service.bridgemanagement.kurata.jp.net/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bridgemanagement.kurata.jp.net/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://service.bridgemanagement.kurata.jp.net/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bridgemanagement.kurata.jp.net/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.bridgemanagement.kurata.jp.net/")]
    public partial class bridge : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private int ageField;
        
        private bool ageFieldSpecified;
        
        private decimal bridgelengthField;
        
        private bool bridgelengthFieldSpecified;
        
        private string bridgenameField;
        
        private string bridgestructureField;
        
        private decimal bridgewidthField;
        
        private bool bridgewidthFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string latitudeField;
        
        private int ledgernumberField;
        
        private bool ledgernumberFieldSpecified;
        
        private string longitudeField;
        
        private string lowermaterialField;
        
        private int madeField;
        
        private bool madeFieldSpecified;
        
        private int managementnumberField;
        
        private bool managementnumberFieldSpecified;
        
        private string memoField;
        
        private string officeField;
        
        private string routeField;
        
        private int spanField;
        
        private bool spanFieldSpecified;
        
        private string uppermaterialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ageSpecified {
            get {
                return this.ageFieldSpecified;
            }
            set {
                this.ageFieldSpecified = value;
                this.RaisePropertyChanged("ageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal bridgelength {
            get {
                return this.bridgelengthField;
            }
            set {
                this.bridgelengthField = value;
                this.RaisePropertyChanged("bridgelength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bridgelengthSpecified {
            get {
                return this.bridgelengthFieldSpecified;
            }
            set {
                this.bridgelengthFieldSpecified = value;
                this.RaisePropertyChanged("bridgelengthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string bridgename {
            get {
                return this.bridgenameField;
            }
            set {
                this.bridgenameField = value;
                this.RaisePropertyChanged("bridgename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string bridgestructure {
            get {
                return this.bridgestructureField;
            }
            set {
                this.bridgestructureField = value;
                this.RaisePropertyChanged("bridgestructure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal bridgewidth {
            get {
                return this.bridgewidthField;
            }
            set {
                this.bridgewidthField = value;
                this.RaisePropertyChanged("bridgewidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bridgewidthSpecified {
            get {
                return this.bridgewidthFieldSpecified;
            }
            set {
                this.bridgewidthFieldSpecified = value;
                this.RaisePropertyChanged("bridgewidthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int ledgernumber {
            get {
                return this.ledgernumberField;
            }
            set {
                this.ledgernumberField = value;
                this.RaisePropertyChanged("ledgernumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ledgernumberSpecified {
            get {
                return this.ledgernumberFieldSpecified;
            }
            set {
                this.ledgernumberFieldSpecified = value;
                this.RaisePropertyChanged("ledgernumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string lowermaterial {
            get {
                return this.lowermaterialField;
            }
            set {
                this.lowermaterialField = value;
                this.RaisePropertyChanged("lowermaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int made {
            get {
                return this.madeField;
            }
            set {
                this.madeField = value;
                this.RaisePropertyChanged("made");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool madeSpecified {
            get {
                return this.madeFieldSpecified;
            }
            set {
                this.madeFieldSpecified = value;
                this.RaisePropertyChanged("madeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int managementnumber {
            get {
                return this.managementnumberField;
            }
            set {
                this.managementnumberField = value;
                this.RaisePropertyChanged("managementnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool managementnumberSpecified {
            get {
                return this.managementnumberFieldSpecified;
            }
            set {
                this.managementnumberFieldSpecified = value;
                this.RaisePropertyChanged("managementnumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string office {
            get {
                return this.officeField;
            }
            set {
                this.officeField = value;
                this.RaisePropertyChanged("office");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string route {
            get {
                return this.routeField;
            }
            set {
                this.routeField = value;
                this.RaisePropertyChanged("route");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int span {
            get {
                return this.spanField;
            }
            set {
                this.spanField = value;
                this.RaisePropertyChanged("span");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool spanSpecified {
            get {
                return this.spanFieldSpecified;
            }
            set {
                this.spanFieldSpecified = value;
                this.RaisePropertyChanged("spanSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string uppermaterial {
            get {
                return this.uppermaterialField;
            }
            set {
                this.uppermaterialField = value;
                this.RaisePropertyChanged("uppermaterial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBridgeList", WrapperNamespace="http://service.bridgemanagement.kurata.jp.net/", IsWrapped=true)]
    public partial class getBridgeListRequest {
        
        public getBridgeListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBridgeListResponse", WrapperNamespace="http://service.bridgemanagement.kurata.jp.net/", IsWrapped=true)]
    public partial class getBridgeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bridgemanagement.kurata.jp.net/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bridgeList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BridgeWebServiceCSharpSample.BridgeServiceReference.bridge[] @return;
        
        public getBridgeListResponse() {
        }
        
        public getBridgeListResponse(BridgeWebServiceCSharpSample.BridgeServiceReference.bridge[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BridgeWebServiceChannel : BridgeWebServiceCSharpSample.BridgeServiceReference.BridgeWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BridgeWebServiceClient : System.ServiceModel.ClientBase<BridgeWebServiceCSharpSample.BridgeServiceReference.BridgeWebService>, BridgeWebServiceCSharpSample.BridgeServiceReference.BridgeWebService {
        
        public BridgeWebServiceClient() {
        }
        
        public BridgeWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BridgeWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BridgeWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BridgeWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BridgeWebServiceCSharpSample.BridgeServiceReference.helloResponse BridgeWebServiceCSharpSample.BridgeServiceReference.BridgeWebService.hello(BridgeWebServiceCSharpSample.BridgeServiceReference.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            BridgeWebServiceCSharpSample.BridgeServiceReference.helloRequest inValue = new BridgeWebServiceCSharpSample.BridgeServiceReference.helloRequest();
            inValue.name = name;
            BridgeWebServiceCSharpSample.BridgeServiceReference.helloResponse retVal = ((BridgeWebServiceCSharpSample.BridgeServiceReference.BridgeWebService)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BridgeWebServiceCSharpSample.BridgeServiceReference.helloResponse> BridgeWebServiceCSharpSample.BridgeServiceReference.BridgeWebService.helloAsync(BridgeWebServiceCSharpSample.BridgeServiceReference.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<BridgeWebServiceCSharpSample.BridgeServiceReference.helloResponse> helloAsync(string name) {
            BridgeWebServiceCSharpSample.BridgeServiceReference.helloRequest inValue = new BridgeWebServiceCSharpSample.BridgeServiceReference.helloRequest();
            inValue.name = name;
            return ((BridgeWebServiceCSharpSample.BridgeServiceReference.BridgeWebService)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListResponse BridgeWebServiceCSharpSample.BridgeServiceReference.BridgeWebService.getBridgeList(BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListRequest request) {
            return base.Channel.getBridgeList(request);
        }
        
        public BridgeWebServiceCSharpSample.BridgeServiceReference.bridge[] getBridgeList() {
            BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListRequest inValue = new BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListRequest();
            BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListResponse retVal = ((BridgeWebServiceCSharpSample.BridgeServiceReference.BridgeWebService)(this)).getBridgeList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListResponse> BridgeWebServiceCSharpSample.BridgeServiceReference.BridgeWebService.getBridgeListAsync(BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListRequest request) {
            return base.Channel.getBridgeListAsync(request);
        }
        
        public System.Threading.Tasks.Task<BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListResponse> getBridgeListAsync() {
            BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListRequest inValue = new BridgeWebServiceCSharpSample.BridgeServiceReference.getBridgeListRequest();
            return ((BridgeWebServiceCSharpSample.BridgeServiceReference.BridgeWebService)(this)).getBridgeListAsync(inValue);
        }
    }
}
